DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS
users(
  id SERIAL PRIMARY KEY NOT NULL,
  quote VARCHAR(256) NOT NULL,
  character VARCHAR(256) NOT NULL,
  image TEXT NOT NULL,
  characterDirection BOOLEAN NOT NULL DEFAULT true
);